version: '3'

services:
  strapi:
    container_name: strapi
    build:
      context: .
      dockerfile: backend-dialisis/Dockerfile
    restart: always
    environment:
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=web_dialisis
      - DATABASE_USERNAME=Admin
      - DATABASE_PASSWORD=passpass
    ports:
      - 1337:1337
    volumes:
      - ./backend-dialisis:/srv/app
    depends_on:
      - db

  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: web_dialisis
      MYSQL_USER: Admin
      MYSQL_PASSWORD: passpass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql
      
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend-dialisis/Dockerfile
    restart: always
    ports: 
      - 3000:3000
    depends_on: 
      - strapi
    volumes:
      - ./frontend-dialisis:/srv/frontend

volumes: 
  db:
    driver: local
