name: GitHub Actions Backend
on: [push, commit]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend-dialisis
    steps:
      - uses: actions/checkout@main
      - name: set up node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: install dependencies
        run: npm i
      - name: setup mysql
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '5.6'
          mysql database: 'web_dialisis_test'
          mysql user: ${{ secrets.DatabaseUser }}
          mysql password: ${{ secrets.DatabasePassword }}
      - name: test
        run: npm test
